default: &default
  adapter: mysql2
  host: mysql
  username: root 
  password:
  
development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3

test:
  <<: *default
  database: blog_test 

production:
  <<: *default
  database: blog_production

